#!/bin/sh
set -e

go build -o bin/broadcast ./cmd/broadcast/*.go
./bin/maelstrom/maelstrom test -w broadcast --bin bin/broadcast --node-count 1 --time-limit 20 --rate 10
./bin/maelstrom/maelstrom test -w broadcast --bin bin/broadcast --node-count 5 --time-limit 20 --rate 10
./bin/maelstrom/maelstrom test -w broadcast --bin bin/broadcast --node-count 5 --time-limit 20 --rate 10 --nemesis partition
