#!/bin/sh
set -e

./scripts/build
./scripts/cleanup

LOG_DIR=$(pwd)/log ./bin/maelstrom/maelstrom test -w broadcast --bin bin/gossip-glomers --node-count 1 --time-limit 20 --rate 10
LOG_DIR=$(pwd)/log ./bin/maelstrom/maelstrom test -w broadcast --bin bin/gossip-glomers --node-count 5 --time-limit 20 --rate 10
LOG_DIR=$(pwd)/log ./bin/maelstrom/maelstrom test -w broadcast --bin bin/gossip-glomers --node-count 5 --time-limit 20 --rate 10 --nemesis partition
