#!/bin/sh
set -e

go build -o bin/gcount ./cmd/gcount/*.go

# Run a few times since it can succeed as a false positive
./bin/maelstrom/maelstrom test -w g-counter --bin  bin/gcount --node-count 3 --rate 100 --time-limit 20 --nemesis partition
./bin/maelstrom/maelstrom test -w g-counter --bin  bin/gcount --node-count 3 --rate 100 --time-limit 20 --nemesis partition
./bin/maelstrom/maelstrom test -w g-counter --bin  bin/gcount --node-count 3 --rate 100 --time-limit 20 --nemesis partition
