#!/bin/sh
set -e

./scripts/build
./scripts/cleanup

# Run a few times since it can succeed as a false positive
LOG_DIR=$(pwd)/log GCOUNTER=true ./bin/maelstrom/maelstrom test -w g-counter --bin bin/gossip-glomers --node-count 3 --rate 100 --time-limit 20 --nemesis partition
LOG_DIR=$(pwd)/log GCOUNTER=true ./bin/maelstrom/maelstrom test -w g-counter --bin bin/gossip-glomers --node-count 3 --rate 100 --time-limit 20 --nemesis partition
LOG_DIR=$(pwd)/log GCOUNTER=true ./bin/maelstrom/maelstrom test -w g-counter --bin bin/gossip-glomers --node-count 3 --rate 100 --time-limit 20 --nemesis partition
