#!/bin/sh
set -e

go install ./maelstrom-unique-ids
cd maelstrom
./maelstrom test -w unique-ids --bin $GOBIN/maelstrom-unique-ids --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition