#!/bin/sh
set -e

./scripts/build
./scripts/cleanup

./bin/maelstrom/maelstrom test -w unique-ids --bin bin/gossip-glomers --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition
